"""Jurisdiction source manifest model.

A :class:`SourceEntry` describes one official or high-value source for a
jurisdiction (regulator page, licensing registry, testing rules, recall
portal, COA repository, open-data API, ...). A :class:`SourceManifest`
groups them per jurisdiction and carries a ``researched`` flag so stub
manifests for un-researched states are never mistaken for audited ones.

Source classes are controlled vocabulary (see SOURCE_CLASSES); unknown
classes fail validation. URLs are normalized (scheme required) and each
source must declare at least a name, authority, and retrieval metadata.

Manifests live under ``data/source-manifests/<state>.json``; stubs under
``data/source-manifests/stubs/<state>.json``. Stubs are generated by
``scripts/source_manifest.py --stubs`` and must never claim research they
did not receive.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Optional

from .core import IngestError

SOURCE_CLASSES = [
    "regulator-homepage",
    "statutes",
    "administrative-regulations",
    "guidance",
    "licensing-registry",
    "license-download",
    "testing-laboratory-registry",
    "testing-rules",
    "mandatory-analyte-panels",
    "action-limits",
    "recalls",
    "enforcement-actions",
    "product-databases",
    "public-records-portal",
    "seed-to-sale-reference",
    "accreditation",
    "coa-repositories",
    "lab-verification-portal",
    "producer-coa-portal",
    "open-data-api",
    "downloadable-dataset",
    "reports",
    "other",
]

RETRIEVAL_METHODS = [
    "http-get", "http-post", "api", "manual-review", "ftp", "s3-bucket",
    "unknown",
]

ARCHIVAL_STRATEGIES = [
    "sha256-immutable", "dated-dir", "none", "wayback", "unknown",
]

FORMATS = ["csv", "json", "xlsx", "xml", "pdf", "html", "zip", "api", "other"]

_URL_RE = re.compile(r"^https?://", re.IGNORECASE)


@dataclass
class SourceEntry:
    """One declared source for a jurisdiction."""

    name: str
    authority: str                      # who publishes it (regulator, lab, producer)
    url: str
    source_class: str = "other"
    machine_readable: bool = False
    authentication_required: bool = False
    format: str = "html"
    refresh_cadence: str = ""
    discovered_date: str = ""
    last_checked_date: str = ""
    retrieval_method: str = "http-get"
    archival_strategy: str = "sha256-immutable"
    licensing_redistribution_caveat: str = ""
    notes: str = ""

    def validate(self) -> list[str]:
        problems: list[str] = []
        if not self.name.strip():
            problems.append("source name is required")
        if not self.authority.strip():
            problems.append(f"{self.name}: authority is required")
        if not _URL_RE.match(self.url.strip()):
            problems.append(f"{self.name}: url must be http(s)")
        if self.source_class not in SOURCE_CLASSES:
            problems.append(f"{self.name}: unknown source_class {self.source_class!r}")
        if self.retrieval_method not in RETRIEVAL_METHODS:
            problems.append(f"{self.name}: unknown retrieval_method {self.retrieval_method!r}")
        if self.archival_strategy not in ARCHIVAL_STRATEGIES:
            problems.append(
                f"{self.name}: unknown archival_strategy {self.archival_strategy!r}"
            )
        return problems

    def to_dict(self) -> dict:
        return {
            "name": self.name, "authority": self.authority, "url": self.url,
            "source_class": self.source_class,
            "machine_readable": self.machine_readable,
            "authentication_required": self.authentication_required,
            "format": self.format, "refresh_cadence": self.refresh_cadence,
            "discovered_date": self.discovered_date,
            "last_checked_date": self.last_checked_date,
            "retrieval_method": self.retrieval_method,
            "archival_strategy": self.archival_strategy,
            "licensing_redistribution_caveat": self.licensing_redistribution_caveat,
            "notes": self.notes,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "SourceEntry":
        return cls(**{k: data.get(k, "") for k in (
            "name", "authority", "url", "source_class", "machine_readable",
            "authentication_required", "format", "refresh_cadence",
            "discovered_date", "last_checked_date", "retrieval_method",
            "archival_strategy", "licensing_redistribution_caveat", "notes",
        )})


@dataclass
class SourceManifest:
    """A jurisdiction's declared source inventory."""

    state: str
    regulator_name: str = ""
    regulator_url: str = ""
    researched: bool = False
    research_status: str = ""           # e.g. "not yet researched" | "verified 2026-08-09"
    updated_date: str = ""
    sources: list[SourceEntry] = field(default_factory=list)

    def validate(self) -> list[str]:
        problems: list[str] = []
        if not self.state.strip():
            problems.append("state is required")
        if self.researched and not self.sources:
            problems.append(f"{self.state}: researched manifest has no sources")
        if not self.researched and self.sources:
            problems.append(
                f"{self.state}: stub manifest must not list sources it was not researched for"
            )
        if self.researched and not self.updated_date:
            problems.append(f"{self.state}: researched manifest missing updated_date")
        for source in self.sources:
            problems.extend(source.validate())
        return problems

    def to_dict(self) -> dict:
        return {
            "schema_version": 1,
            "state": self.state,
            "regulator_name": self.regulator_name,
            "regulator_url": self.regulator_url,
            "researched": self.researched,
            "research_status": self.research_status,
            "updated_date": self.updated_date,
            "sources": [s.to_dict() for s in self.sources],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "SourceManifest":
        return cls(
            state=data.get("state", ""),
            regulator_name=data.get("regulator_name", ""),
            regulator_url=data.get("regulator_url", ""),
            researched=bool(data.get("researched")),
            research_status=data.get("research_status", ""),
            updated_date=data.get("updated_date", ""),
            sources=[SourceEntry.from_dict(s) for s in data.get("sources", [])],
        )


# ---------------------------------------------------------------------------
# Persistence / rendering
# ---------------------------------------------------------------------------


def write_manifest(path: Path, manifest: SourceManifest) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(manifest.to_dict(), handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    return path


def read_manifest(path: Path) -> SourceManifest:
    return SourceManifest.from_dict(json.loads(Path(path).read_text(encoding="utf-8")))


def render_manifest_markdown(manifest: SourceManifest) -> str:
    """Human-readable source inventory for reports and knowledge pages."""
    lines = [
        f"# Source Manifest — {manifest.state}",
        "",
        f"- Regulator: {manifest.regulator_name or '—'}",
        f"- Regulator URL: {manifest.regulator_url or '—'}",
        f"- Research status: {manifest.research_status or ('researched' if manifest.researched else 'not yet researched')}",
        f"- Updated: {manifest.updated_date or '—'}",
        f"- Sources declared: {len(manifest.sources)}",
        "",
    ]
    if manifest.sources:
        lines += [
            "| Source | Authority | Class | URL | Machine-readable | Format | Discovered | Last checked |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
        def _cell(value: str) -> str:
            return str(value).replace("|", "\\|")

        for source in sorted(manifest.sources, key=lambda s: (s.source_class, s.name)):
            lines.append(
                f"| {_cell(source.name)} "
                f"| {_cell(source.authority)} "
                f"| {source.source_class} "
                f"| <{source.url}> "
                f"| {'yes' if source.machine_readable else 'no'} "
                f"| {source.format} "
                f"| {source.discovered_date or '—'} "
                f"| {source.last_checked_date or '—'} |"
            )
    return "\n".join(lines) + "\n"


def today_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def build_stub_manifest(state: str, *, regulator_name: str = "") -> SourceManifest:
    """A manifest for a state that has NOT been researched.

    Deliberately carries no sources and no regulator claims beyond a plain
    jurisdiction name; ``researched=False`` blocks it from being treated as
    evidence.
    """
    return SourceManifest(
        state=state,
        regulator_name=regulator_name,
        researched=False,
        research_status="not yet researched — stub only",
        updated_date=today_iso(),
        sources=[],
    )


def validate_manifest_file(path: Path) -> list[str]:
    return read_manifest(path).validate()


__all__ = [
    "SOURCE_CLASSES", "SourceEntry", "SourceManifest", "write_manifest",
    "read_manifest", "render_manifest_markdown", "build_stub_manifest",
    "validate_manifest_file", "today_iso",
]
